### PR TITLE
Allow built-in root certs to be overrided via constructor

### PR DESCRIPTION
**Pull request by ravelab**
in the style of https://github.com/arduino-libraries/ArduinoBearSSL/commit/8ad6c4805fa28c3132e414993830fbab503fed5e

### CODE REVIEW

**Comment by sandeepmistry** [comment]
Hi @ravelab,

Thanks for taking the time to submit this pull request!

I think we're going to need some more changes however, since `_rootCertsLoaded` is static if two `NBSSLClient`'s are used with different sets of root certs the second clients certs won't be loaded.

**Comment by ravelab** [comment]
Hi @sandeepmistry 

Would it be OK if we change _rootCertsLoaded to instance variable? So if sets of root certs are different, they will be loaded.  If they are the same, they will be loaded multiple times. (Which should be OK with the modem, right?)

**Comment by sandeepmistry** [comment]
> Would it be OK if we change _rootCertsLoaded to instance variable

I'd prefer not to do this, because it will cause slow downs if there are multiple client instances using the default certs.

I would expect the following behaviour:
1) If the default certs are used, they are only loaded once
2) For each client with custom certs, the certs are only loaded once.

I think this can be achieved adding some additional member vars to the class. What do you think?

**Comment by ravelab** [comment]
It sounds good but might take me a while to think about it and update the implementation. The goal is to minimize ROM usage and load time. I don't see why multiple clients would point to different root certs. Maybe that is an acceptable limitation that clients should point to the same custom root certs?

**Comment by ravelab** [comment]
Hi @sandeepmistry 
so are you saying basically two flags, one static _defaultRootCertsLoaded, one member toLoadCustomRootCerts. If calling constructor with custom certs, toLoadCustomRootCerts = true.  If (toLoadCustomRootCerts) load custom, else if (!_defaultRootCertsLoaded) load default   ?

I'm not quite sure what this means "For each client with custom certs, the certs are only loaded once.", do you mean we need to determine if the certs have not been loaded by other clients?

**Comment by sandeepmistry** [comment]
> so are you saying basically two flags, one static _defaultRootCertsLoaded, one member toLoadCustomRootCerts. If calling constructor with custom certs, toLoadCustomRootCerts = true. If (toLoadCustomRootCerts) load custom, else if (!_defaultRootCertsLoaded) load default ?

Yes!

**Comment by ravelab** [comment]
PR updated. The added benefit is that once modem has persistently imported the root certs, users can just do NBSSLClient client(NULL, 0) to not load new ones and connect much faster.

**Comment by mdelain** [comment]
Hello,
I've been hitting the same problem - trying to connect to a MQTT broker using TLS, but without the correct root CA in the `NBRootCerts.h` file. I've solved this by manually adding the certificate in that file.

However, it is not a convenient way when you intend to write a library or a code sample, because it requires every user to do the same.

It should be possible to replicate the AT commands in the code in order to load the missing certificate. But it would be great if you could find a way to wrap up things like you were discussing! :)

**Review by aentinger — APPROVED** [review]
Since @sandeepmistry left the company this PR was left untouched for quite a while. Nonetheless I think it's a good change and I'm going to merge that in  :+1: Thank you @ravelab

**Pull request closed without merging**
