### PR TITLE
Add a choice of what messages to preserve to clear()

### PR DESCRIPTION
**Pull request by janakelarsson**

### CODE REVIEW

**Review by aentinger — CHANGES_REQUESTED** [review]
I'd love if you'd provide `defines`/`constants` with a meaningful name. A `enum` would be even better. Numerical constants alone don't mean much.

**Comment by janakelarsson** [comment]
The numerical constants are fixed in the modem code, listed in the manual. I'll see what I can do.

**Comment by aentinger** [comment]
I know that they are fixed in the modem firmware :wink:, I mean to provide meaningful names for the user of this library.

**Comment by janakelarsson** [comment]
I used a #define, didn't see the enum until now, hope that is ok

**Review by aentinger — APPROVED** [review]
LGTM :+1: Thank you @janakelarsson :rocket:

**Pull request merged**
