### PR TITLE
Enable GSM and UCS2 sms charsets

### PR DESCRIPTION
**Pull request by janakelarsson**
Enable GSM sms charset

### CODE REVIEW

**Comment by janakelarsson** [comment]
Build failed unrelated to the code. Close and reopen to trigger new build.

**Comment by janakelarsson** [comment]
Something has changed at githubusercontent. Rerun test later.

**Comment by janakelarsson** [comment]
Trying again

**Comment by aentinger** [comment]
Hi @janakelarsson :wave: sorry for the long delay. Can you rebase this on the current master thereby solving the merge conflicts (which came about by me merging your other outstandings PRs). If everything still works afterwards we can merge that one in. After that @CCorrado we can move ahead and make a new release.

**Comment by CCorrado** [comment]
Thank you @aentinger! Much appreciated to @janakelarsson as well!

**Review by aentinger — APPROVED** [review]
LGTM :+1: Thank you @janakelarsson :rocket:

**Pull request merged**
